// 网页桌面图标模板（中文模式）
// 网格：25 列 (0-24) × 11 行 (0-10)，一列一列填充
// iconUrl 默认 = 站点根域/favicon.ico（浏览器自动 fallback，无需联网提取）
// AI 对话 search URL 采用已验证的 ?q=%s 配置（油猴/前端解析自动发问）

export const DEFAULT_FOLDERS_ZH = [
{id: "f_girl", startRow: 0, startCol: 0, endRow: 10, endCol: 1, titleTop: "种草/社交", titleBottom: "",},
{id: "f_search", startRow: 0, startCol: 2, endRow: 10, endCol: 3, titleTop: "搜索/AI", titleBottom: "",},
{id: "f_video", startRow: 0, startCol: 4, endRow: 10, endCol: 5, titleTop: "视频/音乐", titleBottom: "",},
{id: "f_life", startRow: 0, startCol: 6, endRow: 10, endCol: 7, titleTop: "购物/生活", titleBottom: "",},
{id: "f_job", startRow: 0, startCol: 8, endRow: 10, endCol: 8, titleTop: "招聘", titleBottom: "",},
{id: "f_office", startRow: 0, startCol: 9, endRow: 10, endCol: 10, titleTop: "办公", titleBottom: "",},
{id: "f_dev", startRow: 0, startCol: 21, endRow: 10, endCol: 23, titleTop: "开发", titleBottom: "",},
{id: "f_sys", startRow: 0, startCol: 24, endRow: 10, endCol: 24, titleTop: "系统", titleBottom: "",}
];

export const DEFAULT_ICONS_ZH = [
{id: "g0", name: "小红书", type: "custom", fileId: null, iconUrl: "https://www.xiaohongshu.com/favicon.ico", darkFileId: null, darkIconUrl: "", url: "https://www.xiaohongshu.com/explore", search: false, row: 0, col: 0,},
{id: "g1", name: "微博", type: "custom", fileId: null, iconUrl: "https://weibo.com/favicon.ico", darkFileId: null, darkIconUrl: "", url: "https://weibo.com/", search: false, row: 1, col: 0,},
{id: "g2", name: "知乎", fileId: null, iconUrl: "https://www.zhihu.com/favicon.ico", url: "https://www.zhihu.com/search?type=content&q=%s", search: true, row: 2, col: 0, type: "custom",},
{id: "g3", name: "豆瓣", type: "custom", fileId: null, iconUrl: "https://www.douban.com/favicon.ico", darkFileId: null, darkIconUrl: "", url: "https://www.douban.com/", search: false, row: 3, col: 0,},
{id: "g4", name: "LOFTER", fileId: null, iconUrl: "https://www.lofter.com/favicon.ico", url: "https://www.lofter.com/", search: false, row: 4, col: 0, type: "custom",},
{id: "g5", name: "堆糖", type: "custom", fileId: null, iconUrl: "https://c-ssl.dtstatic.com/uploads/icons/duitang_favicon.ico", darkFileId: null, darkIconUrl: "", url: "https://www.duitang.com/", search: false, row: 5, col: 0,},
{id: "g6", name: "花瓣", fileId: null, iconUrl: "https://huaban.com/favicon.ico", url: "https://huaban.com/", search: false, row: 6, col: 0, type: "custom",},
{id: "g7", name: "美图秀秀", fileId: null, iconUrl: "https://xiuxiu.web.meitu.com/favicon.ico", url: "https://xiuxiu.web.meitu.com/", search: false, row: 7, col: 0, type: "custom",},
{id: "g8", name: "醒图", fileId: null, iconUrl: "https://www.retouchpics.com/favicon.ico", url: "https://www.retouchpics.com/", search: false, row: 8, col: 0, type: "custom",},
{id: "g9", name: "剪映", type: "custom", fileId: null, iconUrl: "https://lf3-s.vlabstatic.com/obj/vilab-static/ies/ulike/web/resource/fe_official/assets/imgs/lv/favicon.ico", darkFileId: null, darkIconUrl: "", url: "https://www.capcut.cn/", search: false, row: 9, col: 0,},
{id: "g10", name: "稿定", fileId: null, iconUrl: "https://www.gaoding.com/favicon.ico", url: "https://www.gaoding.com/", search: false, row: 10, col: 0, type: "custom",},
{id: "g11", name: "抖音", fileId: null, iconUrl: "https://www.douyin.com/favicon.ico", url: "https://www.douyin.com/", search: false, row: 0, col: 1, type: "custom",},
{id: "g12", name: "快手", fileId: null, iconUrl: "https://www.kuaishou.com/favicon.ico", url: "https://www.kuaishou.com/", search: false, row: 1, col: 1, type: "custom",},
{id: "g13", name: "B站", fileId: null, iconUrl: "https://www.bilibili.com/favicon.ico", url: "https://search.bilibili.com/all?keyword=%s", search: true, row: 2, col: 1, type: "custom",},
{id: "g14", name: "微信读书", fileId: null, iconUrl: "https://weread.qq.com/favicon.ico", url: "https://weread.qq.com/", search: false, row: 3, col: 1, type: "custom",},
{id: "g15", name: "得物", type: "custom", fileId: null, iconUrl: "https://www.dewu.com/static/favicon.ico", darkFileId: null, darkIconUrl: "", url: "https://www.dewu.com/", search: false, row: 4, col: 1,},
{id: "g16", name: "蘑菇街", type: "custom", fileId: null, iconUrl: "https://s10.mogucdn.com/mlcdn/c45406/170401_16fj5k6k4174bfd21d03a4gf6a7hg_48x48.png", darkFileId: null, darkIconUrl: "", url: "https://www.mogu.com/", search: false, row: 5, col: 1,},
{id: "g17", name: "唯品会", fileId: null, iconUrl: "https://www.vip.com/favicon.ico", url: "https://www.vip.com/", search: false, row: 6, col: 1, type: "custom",},
{id: "g18", name: "下厨房", fileId: null, iconUrl: "https://www.xiachufang.com/favicon.ico", url: "https://www.xiachufang.com/", search: false, row: 7, col: 1, type: "custom",},
{id: "g19", name: "Keep", type: "custom", fileId: null, iconUrl: "https://www.keep.com/icons/favicon.ico", darkFileId: null, darkIconUrl: "", url: "https://www.keep.com/", search: false, row: 8, col: 1,},
{id: "g20", name: "美柚", fileId: null, iconUrl: "https://www.meiyou.com/favicon.ico", url: "https://www.meiyou.com/", search: false, row: 9, col: 1, type: "custom",},
{id: "g21", name: "网易云", fileId: null, iconUrl: "https://music.163.com/favicon.ico", url: "https://music.163.com/", search: false, row: 10, col: 1, type: "custom",},
{id: "s0", name: "百度", fileId: null, iconUrl: "https://www.baidu.com/favicon.ico", url: "https://www.baidu.com/s?wd=%s", search: true, row: 0, col: 2, type: "custom",},
{id: "s1", name: "必应", fileId: null, iconUrl: "https://cn.bing.com/favicon.ico", url: "https://cn.bing.com/search?q=%s", search: true, row: 1, col: 2, type: "custom",},
{id: "s2", name: "搜狗", fileId: null, iconUrl: "https://www.sogou.com/favicon.ico", url: "https://www.sogou.com/web?query=%s", search: true, row: 2, col: 2, type: "custom",},
{id: "s3", name: "360", fileId: null, iconUrl: "https://www.so.com/favicon.ico", url: "https://www.so.com/s?q=%s", search: true, row: 3, col: 2, type: "custom",},
{id: "s4", name: "头条", fileId: null, iconUrl: "https://so.toutiao.com/favicon.ico", url: "https://so.toutiao.com/search?keyword=%s", search: true, row: 4, col: 2, type: "custom",},
{id: "s5", name: "秘塔", fileId: null, iconUrl: "https://metaso.cn/favicon.ico", url: "https://metaso.cn/?q=%s", search: true, row: 5, col: 2, type: "custom",},
{id: "s6", name: "DeepSeek", type: "custom", fileId: null, iconUrl: "https://fe-static.deepseek.com/chat/favicon.svg", darkFileId: null, darkIconUrl: "", url: "https://chat.deepseek.com/?q=%s", search: true, row: 6, col: 2,},
{id: "s7", name: "Google", type: "custom", fileId: null, iconUrl: "https://www.google.com/favicon.ico", darkFileId: null, darkIconUrl: "", url: "https://www.google.com/?q=%s", search: true, row: 7, col: 2,},
{id: "s8", name: "Gemini", fileId: null, iconUrl: "https://gemini.google.com/favicon.ico", url: "https://gemini.google.com/app?q=%s", search: true, row: 8, col: 2, type: "custom",},
{id: "s9", name: "ChatGPT", fileId: null, iconUrl: "https://chatgpt.com/favicon.ico", url: "https://chatgpt.com/?q=%s", search: true, row: 9, col: 2, type: "custom",},
{id: "s10", name: "Claude", fileId: null, iconUrl: "https://claude.ai/favicon.ico", url: "https://claude.ai/new?q=%s", search: true, row: 10, col: 2, type: "custom",},
{id: "s11", name: "豆包", type: "custom", fileId: null, iconUrl: "https://lf-flow-web-cdn.doubao.com/obj/flow-doubao/favicon/new-doubao/64x64.png", darkFileId: null, darkIconUrl: "", url: "https://www.doubao.com/", search: false, row: 0, col: 3,},
{id: "s12", name: "Kimi", type: "custom", fileId: null, iconUrl: "https://www.kimi.com/favicon.ico", darkFileId: null, darkIconUrl: "", url: "https://www.kimi.com/", search: false, row: 1, col: 3,},
{id: "s13", name: "元宝", type: "custom", fileId: null, iconUrl: "https://yuanbao.tencent.com/favicon.ico", darkFileId: null, darkIconUrl: "", url: "https://yuanbao.tencent.com/", search: false, row: 2, col: 3,},
{id: "s14", name: "千问", type: "custom", fileId: null, iconUrl: "https://img.alicdn.com/imgextra/i2/O1CN01taBbMS1CfyJoOt0lB_!!6000000000109-2-tps-80-80.png", darkFileId: null, darkIconUrl: "", url: "https://www.qianwen.com/", search: false, row: 3, col: 3,},
{id: "s15", name: "文心", type: "custom", fileId: null, iconUrl: "https://www.baidu.com//favicon.ico", darkFileId: null, darkIconUrl: "", url: "https://wenxin.baidu.com/", search: false, row: 4, col: 3,},
{id: "s16", name: "智谱", fileId: null, iconUrl: "https://chatglm.cn/favicon.ico", url: "https://chatglm.cn/", search: false, row: 5, col: 3, type: "custom",},
{id: "s17", name: "腾讯文档", type: "custom", fileId: null, iconUrl: "https://docs.idqqimg.com/tim/docs/desktop/favicon.ico", darkFileId: null, darkIconUrl: "", url: "https://docs.qq.com/", search: false, row: 6, col: 3,},
{id: "s18", name: "飞书", fileId: null, iconUrl: "https://www.feishu.cn/favicon.ico", url: "https://www.feishu.cn/", search: false, row: 7, col: 3, type: "custom",},
{id: "s19", name: "扣子", type: "custom", fileId: null, iconUrl: "https://www.coze.cn/space-intro/favicon.ico", darkFileId: null, darkIconUrl: "", url: "https://www.coze.cn/", search: false, row: 8, col: 3,},
{id: "s20", name: "Trae", type: "custom", fileId: null, iconUrl: "https://lf-cdn.trae.com.cn/obj/trae-com-cn/trae_website_prod_cn/favicon.png", darkFileId: null, darkIconUrl: "", url: "https://www.trae.cn/", search: false, row: 9, col: 3,},
{id: "s21", name: "Cursor", fileId: null, iconUrl: "https://cursor.com/favicon.ico", url: "https://cursor.com/", search: false, row: 10, col: 3, type: "custom",},
{id: "m0", name: "B站", fileId: null, iconUrl: "https://www.bilibili.com/favicon.ico", url: "https://www.bilibili.com/", search: false, row: 0, col: 4, type: "custom",},
{id: "m1", name: "抖音", fileId: null, iconUrl: "https://www.douyin.com/favicon.ico", url: "https://www.douyin.com/", search: false, row: 1, col: 4, type: "custom",},
{id: "m2", name: "快手", fileId: null, iconUrl: "https://www.kuaishou.com/favicon.ico", url: "https://www.kuaishou.com/", search: false, row: 2, col: 4, type: "custom",},
{id: "m3", name: "优酷", fileId: null, iconUrl: "https://www.youku.com/favicon.ico", url: "https://www.youku.com/", search: false, row: 3, col: 4, type: "custom",},
{id: "m4", name: "腾讯视频", fileId: null, iconUrl: "https://v.qq.com/favicon.ico", url: "https://v.qq.com/", search: false, row: 4, col: 4, type: "custom",},
{id: "m5", name: "爱奇艺", fileId: null, iconUrl: "https://www.iqiyi.com/favicon.ico", url: "https://www.iqiyi.com/", search: false, row: 5, col: 4, type: "custom",},
{id: "m6", name: "芒果TV", fileId: null, iconUrl: "https://www.mgtv.com/favicon.ico", url: "https://www.mgtv.com/", search: false, row: 6, col: 4, type: "custom",},
{id: "m7", name: "网易云", fileId: null, iconUrl: "https://music.163.com/favicon.ico", url: "https://music.163.com/", search: false, row: 7, col: 4, type: "custom",},
{id: "m8", name: "QQ音乐", fileId: null, iconUrl: "https://y.qq.com/favicon.ico", url: "https://y.qq.com/", search: false, row: 8, col: 4, type: "custom",},
{id: "m9", name: "酷狗", fileId: null, iconUrl: "https://www.kugou.com/favicon.ico", url: "https://www.kugou.com/", search: false, row: 9, col: 4, type: "custom",},
{id: "m10", name: "酷我", fileId: null, iconUrl: "https://www.kuwo.cn/favicon.ico", url: "https://www.kuwo.cn/", search: false, row: 10, col: 4, type: "custom",},
{id: "m11", name: "AcFun", fileId: null, iconUrl: "https://www.acfun.cn/favicon.ico", url: "https://www.acfun.cn/", search: false, row: 0, col: 5, type: "custom",},
{id: "m12", name: "梨视频", type: "custom", fileId: null, iconUrl: "https://page.pearvideo.com/webres/img/favicon.ico", darkFileId: null, darkIconUrl: "", url: "https://www.pearvideo.com/", search: false, row: 1, col: 5,},
{id: "m13", name: "西瓜视频", fileId: null, iconUrl: "https://www.ixigua.com/favicon.ico", url: "https://www.ixigua.com/", search: false, row: 2, col: 5, type: "custom",},
{id: "m14", name: "微视", type: "custom", fileId: null, iconUrl: "https://i.gtimg.cn/qz-proj/weishi-pc/img/favicon.ico", darkFileId: null, darkIconUrl: "", url: "https://weishi.qq.com/", search: false, row: 3, col: 5,},
{id: "m15", name: "好看视频", fileId: null, iconUrl: "https://haokan.baidu.com/favicon.ico", url: "https://haokan.baidu.com/", search: false, row: 4, col: 5, type: "custom",},
{id: "m16", name: "喜马拉雅", fileId: null, iconUrl: "https://www.ximalaya.com/favicon.ico", url: "https://www.ximalaya.com/", search: false, row: 5, col: 5, type: "custom",},
{id: "m17", name: "蜻蜓FM", fileId: null, iconUrl: "https://www.qingting.fm/favicon.ico", url: "https://www.qingting.fm/", search: false, row: 6, col: 5, type: "custom",},
{id: "m18", name: "猫耳FM", fileId: null, iconUrl: "https://www.missevan.com/favicon.ico", url: "https://www.missevan.com/", search: false, row: 7, col: 5, type: "custom",},
{id: "m19", name: "全民K歌", fileId: null, iconUrl: "https://kg.qq.com/favicon.ico", url: "https://kg.qq.com/", search: false, row: 8, col: 5, type: "custom",},
{id: "m20", name: "斗鱼", fileId: null, iconUrl: "https://www.douyu.com/favicon.ico", url: "https://www.douyu.com/", search: false, row: 9, col: 5, type: "custom",},
{id: "m21", name: "虎牙", fileId: null, iconUrl: "https://www.huya.com/favicon.ico", url: "https://www.huya.com/", search: false, row: 10, col: 5, type: "custom",},
{id: "l0", name: "淘宝", fileId: null, iconUrl: "https://www.taobao.com/favicon.ico", url: "https://s.taobao.com/search?q=%s", search: true, row: 0, col: 6, type: "custom",},
{id: "l1", name: "京东", fileId: null, iconUrl: "https://www.jd.com/favicon.ico", url: "https://search.jd.com/Search?keyword=%s", search: true, row: 1, col: 6, type: "custom",},
{id: "l2", name: "拼多多", type: "custom", fileId: null, iconUrl: "https://www.pinduoduo.com/favicon.png", darkFileId: null, darkIconUrl: "", url: "https://www.pinduoduo.com/", search: false, row: 2, col: 6,},
{id: "l3", name: "唯品会", fileId: null, iconUrl: "https://www.vip.com/favicon.ico", url: "https://www.vip.com/", search: false, row: 3, col: 6, type: "custom",},
{id: "l4", name: "得物", type: "custom", fileId: null, iconUrl: "https://www.dewu.com/static/favicon.ico", darkFileId: null, darkIconUrl: "", url: "https://www.dewu.com/", search: false, row: 4, col: 6,},
{id: "l5", name: "大众点评", type: "custom", fileId: null, iconUrl: "https://h5.dianping.com/favicon.ico", darkFileId: null, darkIconUrl: "", url: "https://www.dianping.com/", search: false, row: 5, col: 6,},
{id: "l6", name: "美团", fileId: null, iconUrl: "https://www.meituan.com/favicon.ico", url: "https://www.meituan.com/", search: false, row: 6, col: 6, type: "custom",},
{id: "l7", name: "饿了么", fileId: null, iconUrl: "https://www.ele.me/favicon.ico", url: "https://www.ele.me/", search: false, row: 7, col: 6, type: "custom",},
{id: "l8", name: "飞猪", type: "custom", fileId: null, iconUrl: "https://img.alicdn.com/imgextra/i1/O1CN01XslwqW1rp2BOz0lt4_!!6000000005679-73-tps-64-64.ico", darkFileId: null, darkIconUrl: "", url: "https://www.fliggy.com/", search: false, row: 8, col: 6,},
{id: "l9", name: "携程", fileId: null, iconUrl: "https://www.ctrip.com/favicon.ico", url: "https://www.ctrip.com/", search: false, row: 9, col: 6, type: "custom",},
{id: "l10", name: "去哪儿", fileId: null, iconUrl: "https://www.qunar.com/favicon.ico", url: "https://www.qunar.com/", search: false, row: 10, col: 6, type: "custom",},
{id: "l11", name: "闲鱼", fileId: null, iconUrl: "https://www.goofish.com/favicon.ico", url: "https://www.goofish.com/", search: false, row: 0, col: 7, type: "custom",},
{id: "l12", name: "转转", fileId: null, iconUrl: "https://www.zhuanzhuan.com/favicon.ico", url: "https://www.zhuanzhuan.com/", search: false, row: 1, col: 7, type: "custom",},
{id: "l13", name: "链家", fileId: null, iconUrl: "https://www.lianjia.com/favicon.ico", url: "https://www.lianjia.com/", search: false, row: 2, col: 7, type: "custom",},
{id: "l14", name: "贝壳", fileId: null, iconUrl: "https://www.ke.com/favicon.ico", url: "https://www.ke.com/", search: false, row: 3, col: 7, type: "custom",},
{id: "l15", name: "马蜂窝", fileId: null, iconUrl: "https://www.mafengwo.cn/favicon.ico", url: "https://www.mafengwo.cn/", search: false, row: 4, col: 7, type: "custom",},
{id: "l16", name: "下厨房", fileId: null, iconUrl: "https://www.xiachufang.com/favicon.ico", url: "https://www.xiachufang.com/", search: false, row: 5, col: 7, type: "custom",},
{id: "l17", name: "豆果", fileId: null, iconUrl: "https://www.douguo.com/favicon.ico", url: "https://www.douguo.com/", search: false, row: 6, col: 7, type: "custom",},
{id: "l18", name: "Keep", type: "custom", fileId: null, iconUrl: "https://www.keep.com/icons/favicon.ico", darkFileId: null, darkIconUrl: "", url: "https://www.keep.com/", search: false, row: 7, col: 7,},
{id: "l19", name: "薄荷健康", type: "custom", fileId: null, iconUrl: "https://www-cdn.boohee.com/public/images/favicon.DRpwKRg1.png", darkFileId: null, darkIconUrl: "", url: "https://www.boohee.com/", search: false, row: 8, col: 7,},
{id: "l20", name: "美柚", fileId: null, iconUrl: "https://www.meiyou.com/favicon.ico", url: "https://www.meiyou.com/", search: false, row: 9, col: 7, type: "custom",},
{id: "l21", name: "美丽修行", type: "custom", fileId: null, iconUrl: "https://img0.bevol.cn/www.ico.la_af49e6c91a9a793c3aa1e02f8f22f91a_30x30.ico", darkFileId: null, darkIconUrl: "", url: "https://www.bevol.cn/", search: false, row: 10, col: 7,},
, // ===== col 8 招聘 ===== {id: "j0", name: "BOSS直聘", fileId: null, iconUrl: "https://www.zhipin.com/favicon.ico", url: "https://www.zhipin.com/", search: false, row: 0, col: 8,},
{id: "j1", name: "前程无忧", fileId: null, iconUrl: "https://fecdn.51jobcdn.com/fe/public/icon/favicon51_128_128.ico", url: "https://www.51job.com/", search: false, row: 1, col: 8,},
{id: "j2", name: "智联", fileId: null, iconUrl: "https://www.zhaopin.com/favicon.ico", url: "https://www.zhaopin.com/", search: false, row: 2, col: 8,},
{id: "j3", name: "猎聘", fileId: null, iconUrl: "https://concat.lietou-static.com/fe-www-pc/v6/static/images/favicon.371e30de.ico", url: "https://www.liepin.com/", search: false, row: 3, col: 8,},
{id: "j4", name: "拉勾", fileId: null, iconUrl: "https://www.lgstatic.com/lg-www-fed/common/static/favicon_faed927.ico", url: "https://www.lagou.com/wn/", search: false, row: 4, col: 8,},
{id: "j5", name: "牛客", fileId: null, iconUrl: "https://www.nowcoder.com/favicon.ico", url: "https://www.nowcoder.com/", search: false, row: 5, col: 8,},
{id: "j6", name: "国聘", fileId: null, iconUrl: "https://iguopin-base.oss-cn-beijing.aliyuncs.com/406251f705a54f799018bc7ac7c70370/site-logo/20231213/d7bce5f4f7b422cd94ce4d03c2b32852.ico", url: "https://www.iguopin.com/", search: false, row: 6, col: 8,},
{id: "j7", name: "应届生", fileId: null, iconUrl: "https://www.yingjiesheng.com/favicon.ico", url: "https://www.yingjiesheng.com/", search: false, row: 7, col: 8,},
{id: "j8", name: "脉脉", fileId: null, iconUrl: "https://maimai.cn/favicon.ico", url: "https://maimai.cn/", search: false, row: 8, col: 8,},
{id: "j9", name: "公共招聘", fileId: null, iconUrl: "http://job.mohrss.gov.cn/r/cms/www/default/images/rone.ico", url: "http://job.mohrss.gov.cn/", search: false, row: 9, col: 8,},
{id: "j10", name: "58同城", fileId: null, iconUrl: "https://www.58.com/favicon.ico", url: "https://www.58.com/rencai/", search: false, row: 9, col: 8,},
, // ===== col 9 办公 ===== {id: "o0", name: "腾讯文档", iconUrl: "https://docs.idqqimg.com/tim/docs/desktop/favicon.ico", url: "https://docs.qq.com/", search: false, row: 0, col: 9,},
{id: "o1", name: "飞书", iconUrl: "https://www.feishu.cn/favicon.ico", url: "https://www.feishu.cn/", search: false, row: 1, col: 9,},
{id: "o2", name: "钉钉", iconUrl: "https://www.dingtalk.com/favicon.ico", url: "https://www.dingtalk.com/", search: false, row: 2, col: 9,},
{id: "o3", name: "企业微信", iconUrl: "https://work.weixin.qq.com/favicon.ico", url: "https://work.weixin.qq.com/", search: false, row: 3, col: 9,},
{id: "o4", name: "WPS", iconUrl: "https://www.wps.cn/favicon.ico", url: "https://www.wps.cn/", search: false, row: 4, col: 9,},
{id: "o5", name: "石墨", iconUrl: "https://shimo.im/favicon.ico", url: "https://shimo.im/", search: false, row: 5, col: 9,},
{id: "o6", name: "语雀", iconUrl: "https://www.yuque.com/favicon.ico", url: "https://www.yuque.com/", search: false, row: 6, col: 9,},
{id: "o7", name: "Notion", iconUrl: "https://www.notion.com/front-static/favicon.ico", url: "https://www.notion.so/", search: false, row: 7, col: 9,},
{id: "o8", name: "Obsidian", iconUrl: "https://obsidian.md/favicon.ico", url: "https://obsidian.md/", search: false, row: 8, col: 9,},
{id: "o9", name: "有道云", iconUrl: "https://note.youdao.com/favicon.ico", url: "https://note.youdao.com/", search: false, row: 9, col: 9,},
{id: "o10", name: "幕布", iconUrl: "https://mubu.com/favicon.ico", url: "https://mubu.com/", search: false, row: 10, col: 9,},
, // ===== col 10 办公 ===== {id: "o11", name: "ProcessOn", iconUrl: "https://www.processon.com/favicon.ico", url: "https://www.processon.com/", search: false, row: 0, col: 10,},
{id: "o12", name: "墨刀", iconUrl: "https://modao.cc/favicon.ico", url: "https://modao.cc/", search: false, row: 1, col: 10,},
{id: "o13", name: "即时设计", iconUrl: "https://js.design/favicon.ico", url: "https://js.design/", search: false, row: 2, col: 10,},
{id: "o14", name: "稿定", iconUrl: "https://www.gaoding.com/favicon.ico", url: "https://www.gaoding.com/", search: false, row: 3, col: 10,},
{id: "o15", name: "创客贴", iconUrl: "https://www.chuangkit.com/favicon.ico", url: "https://www.chuangkit.com/", search: false, row: 4, col: 10,},
{id: "o16", name: "Canva", iconUrl: "https://www.canva.cn/favicon.ico", url: "https://www.canva.cn/", search: false, row: 5, col: 10,},
{id: "o17", name: "剪映", iconUrl: "https://lf3-s.vlabstatic.com/obj/vilab-static/ies/ulike/web/resource/fe_official/assets/imgs/lv/favicon.ico", url: "https://www.capcut.cn/", search: false, row: 6, col: 10,},
{id: "o18", name: "即梦", iconUrl: "https://lf3-lv-buz.vlabstatic.com/obj/image-lvweb-buz/common/images/dreamina-v1.ico", url: "https://jimeng.jianying.com/", search: false, row: 7, col: 10,},
{id: "o19", name: "通义听悟", iconUrl: "https://g.alicdn.com/idst-fe/mind-meeting-assistant2/0.1.32/favicon.png", url: "https://tingwu.aliyun.com/", search: false, row: 8, col: 10,},
{id: "o20", name: "讯飞听见", iconUrl: "https://www.iflyrec.com/static/imgs/favicon.ico", url: "https://www.iflyrec.com/", search: false, row: 9, col: 10,},
{id: "o21", name: "扫描全能王", iconUrl: "https://www.camscanner.com/favicon.png", url: "https://www.camscanner.com/", search: false, row: 10, col: 10,},
, // ===== col 21 开发 ===== {id: "d0", name: "MDN", fileId: null, iconUrl: "https://developer.mozilla.org/favicon.ico", url: "https://developer.mozilla.org/zh-CN/", search: false, row: 0, col: 21,},
{id: "d1", name: "GitHub", fileId: null, iconUrl: "https://github.com/favicon.ico", url: "https://github.com/", search: false, row: 1, col: 21,},
{id: "d2", name: "Gitee", fileId: null, iconUrl: "https://gitee.com/favicon.ico", url: "https://gitee.com/", search: false, row: 2, col: 21,},
{id: "d3", name: "StackOverflow", fileId: null, iconUrl: "https://stackoverflow.com/favicon.ico", url: "https://stackoverflow.com/search?q=%s", search: true, row: 3, col: 21,},
{id: "d4", name: "npm", fileId: null, iconUrl: "https://static-production.npmjs.com/b0f1a8318363185cc2ea6a40ac23eeb2.png", url: "https://www.npmjs.com/", search: false, row: 4, col: 21,},
{id: "d5", name: "掘金", fileId: null, iconUrl: "https://juejin.cn/favicon.ico", url: "https://juejin.cn/", search: false, row: 5, col: 21,},
{id: "d6", name: "CSDN", fileId: null, iconUrl: "https://blog.csdn.net/favicon.ico", url: "https://blog.csdn.net/", search: false, row: 6, col: 21,},
{id: "d7", name: "博客园", fileId: null, iconUrl: "https://www.cnblogs.com/favicon.ico", url: "https://www.cnblogs.com/", search: false, row: 7, col: 21,},
{id: "d8", name: "CanIUse", fileId: null, iconUrl: "https://caniuse.com/img/favicon-128.png", url: "https://caniuse.com/?search=%s", search: true, row: 8, col: 21,},
{id: "d9", name: "Docker", fileId: null, iconUrl: "https://docs.docker.com/favicon.ico", url: "https://hub.docker.com/", search: false, row: 9, col: 21,},
{id: "d10", name: "PyPI", fileId: null, iconUrl: "https://pypi.org/favicon.ico", url: "https://pypi.org/", search: false, row: 10, col: 21,},
, // ===== col 22 开发 ===== {id: "d11", name: "腾讯云", fileId: null, iconUrl: "https://cloud.tencent.com/favicon.ico", url: "https://cloud.tencent.com/", search: false, row: 0, col: 22,},
{id: "d12", name: "阿里云", fileId: null, iconUrl: "https://img.alicdn.com/tfs/TB1_ZXuNcfpK1RjSZFOXXa6nFXa-32-32.ico", url: "https://home.console.aliyun.com/", search: false, row: 1, col: 22,},
{id: "d13", name: "华为云", fileId: null, iconUrl: "https://www.huaweicloud.com/favicon.ico", url: "https://www.huaweicloud.com/", search: false, row: 2, col: 22,},
{id: "d14", name: "Vercel", fileId: null, iconUrl: "https://vercel.com/favicon.ico", url: "https://vercel.com/", search: false, row: 3, col: 22,},
{id: "d15", name: "LeetCode", fileId: null, iconUrl: "https://leetcode.cn/favicon.ico", url: "https://leetcode.cn/", search: false, row: 4, col: 22,},
{id: "d16", name: "阮一峰ES6", fileId: null, iconUrl: "https://es6.ruanyifeng.com/favicon.ico", url: "https://es6.ruanyifeng.com/", search: false, row: 5, col: 22,},
{id: "d17", name: "Vue", fileId: null, iconUrl: "https://vuejs.org/logo.svg", url: "https://vuejs.org/", search: false, row: 6, col: 22,},
{id: "d18", name: "React", fileId: null, iconUrl: "https://react.dev/favicon.ico", url: "https://react.dev/", search: false, row: 7, col: 22,},
{id: "d19", name: "Vite", fileId: null, iconUrl: "https://vite.dev/logo-without-border.svg", url: "https://vite.dev/", search: false, row: 8, col: 22,},
{id: "d20", name: "Next.js", fileId: null, iconUrl: "https://nextjs.org/favicon.ico", url: "https://nextjs.org/", search: false, row: 9, col: 22,},
{id: "d21", name: "Tailwind", fileId: null, iconUrl: "https://tailwindcss.com/favicon.ico", url: "https://tailwindcss.com/", search: false, row: 10, col: 22,},
, // ===== col 23 开发 ===== {id: "d22", name: "TypeScript", fileId: null, iconUrl: "https://www.typescriptlang.org/favicon.ico", url: "https://www.typescriptlang.org/", search: false, row: 0, col: 23,},
{id: "d23", name: "Rust", fileId: null, iconUrl: "https://rust-lang.org/static/images/favicon.svg", url: "https://www.rust-lang.org/", search: false, row: 1, col: 23,},
{id: "d24", name: "Go", fileId: null, iconUrl: "https://go.dev/favicon.ico", url: "https://go.dev/", search: false, row: 2, col: 23,},
{id: "d25", name: "Python", fileId: null, iconUrl: "https://docs.python.org/favicon.ico", url: "https://docs.python.org/zh-cn/3/", search: false, row: 3, col: 23,},
{id: "d26", name: "Java", fileId: null, iconUrl: "https://docs.oracle.com/favicon.ico", url: "https://docs.oracle.com/en/java/", search: false, row: 4, col: 23,},
{id: "d27", name: "K8s", fileId: null, iconUrl: "https://kubernetes.io/icons/favicon-32.png", url: "https://kubernetes.io/", search: false, row: 5, col: 23,},
{id: "d28", name: "PostgreSQL", fileId: null, iconUrl: "https://www.postgresql.org/favicon.ico", url: "https://www.postgresql.org/", search: false, row: 6, col: 23,},
{id: "d29", name: "Redis", fileId: null, iconUrl: "https://redis.io/favicon.ico", url: "https://redis.io/", search: false, row: 7, col: 23,},
{id: "d30", name: "Spring", fileId: null, iconUrl: "https://spring.io/favicon.svg", url: "https://spring.io/", search: false, row: 8, col: 23,},
{id: "d31", name: "CodePen", fileId: null, iconUrl: "https://codepen.io/favicon.ico", url: "https://codepen.io/", search: false, row: 9, col: 23,},
{id: "d32", name: "jsDelivr", fileId: null, iconUrl: "https://www.jsdelivr.com/favicon.ico", url: "https://www.jsdelivr.com/", search: false, row: 10, col: 23,},
, // ===== col 24 系统（浏览器内部）===== {id: "b0", name: "设置", fileId: null, iconUrl: "⚙️", url: "edge://settings", search: false, row: 0, col: 24,},
{id: "b1", name: "扩展", fileId: null, iconUrl: "🧩", url: "edge://extensions", search: false, row: 1, col: 24,},
{id: "b2", name: "新标签页", fileId: null, iconUrl: "📋", url: "edge://newtab", search: false, row: 2, col: 24,},
{id: "b3", name: "下载", fileId: null, iconUrl: "⚓", url: "edge://downloads", search: false, row: 3, col: 24,},
{id: "b4", name: "收藏", fileId: null, iconUrl: "⭐", url: "edge://bookmarks", search: false, row: 4, col: 24,},
{id: "b5", name: "历史", fileId: null, iconUrl: "🕒", url: "edge://history", search: false, row: 5, col: 24,},
{id: "b6", name: "应用", fileId: null, iconUrl: "📦", url: "edge://apps", search: false, row: 6, col: 24,},
{id: "b7", name: "空白", fileId: null, iconUrl: "📄", url: "about:blank", search: false, row: 7, col: 24,}
];